### ISSUE TITLE
templaterCreateNote does not seem to work

### ISSUE THREAD

**Issue by mProjectsCode** [mProjectsCode/obsidian-meta-bind-plugin#221]
### Discussed in https://github.com/mProjectsCode/obsidian-meta-bind-plugin/discussions/220

<div type='discussions-op-text'>

<sup>Originally posted by **gillesbonnet** February 18, 2024</sup>
Templater buttons do not seem to work for me. I did not succeed to make the [example](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/buttons/#templater-create-note-action) from the doc work. 
Also the example from the [exampleVault](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/tree/master/exampleVault) does not work for me: I downloaded the exampleVault from the Github repository of the project, open it, installed and activated the plugins "Meta Bind" and Templater. Then, in the note "Button Example" there is the button

```meta-bind-button
label: Templater
hidden: false
id: ""
style: default
actions:
  - type: templaterCreateNote
    templateFile: "templates/templater/Templater Template.md"
    fileName: Button Templater Test

```

When I click on it, I receives the popup message: "metaBind | Error while running button action. Check the console for details."
In the console I see this:
<img width="451" alt="image" src="https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/14077290/1c400ded-c060-427c-bd75-89c187cebd6c">

Does someone has a suggestion to try something I might have forgotten?

</div>

**Comment by dzenifr** [comment]
I'm also having issues with the button, and maybe it's me because I can get some buttons to work but not others.

This button works just fine:
```meta-bind-button
label: New Meeting
hidden: false
class: ""
tooltip: ""
id: ""
style: default
actions:
  - type: templaterCreateNote
    templateFile: Template/Template, Meeting.md
    folderPath: Timestamps/Meetings
    fileName: TKTK
    openNote: true
```

This button throws errors:
```meta-bind-button
label: New FIC Note
hidden: false
class: ""
tooltip: ""
id: ""
style: default
actions:
  - type: templaterCreateNote
    templateFile: "Template/Template, FIC Note.md"
    folderPath: Timestamps/FIC Notes
    fileName: "Note"
    openNote: true

```
I tried putting quotes around the templateFile and fileName as in the FAQ, but it didn't seem to make a difference.

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/39705935/62d249ff-ca3d-4de4-ae70-bf0f864ac209)

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/39705935/dde8346f-b0d3-4d45-884e-5e3d7ccd9d69)

It looks like it's looking for the file, not creating it.

**Comment by mProjectsCode** [comment]
How does your template look?

**Comment by ethernic** [comment]
@dzenifr I'm assuming you're using the same Dann Berg template that got me here. The issue is with the template, specifically this line:

```
<% await tp.file.move("/Timestamps/Meetings/" + tp.date.now("YYYY-MM-DD") + " " + tp.file.title) %>
```

Update it to `/Timestamps/FIC Notes/` and you should be good.

**Comment by dzenifr** [comment]
Yep, that's how I got here. However, even after changing that (thank you, btw!) then using the button builder I still end up with this issue. 

FIC Note template:
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/39705935/e207e84b-165c-44bb-ba7c-a415ae679e0e)

Using the button builder, this is the error I get:
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/39705935/1cc04833-8ad8-449a-a5c2-d50d9c84d4ef)

**Comment by ethernic** [comment]
Is your vault stored at `I:\Visual\Documents\Obsidian Vault` and named `Beginning`? Just want to make sure the path is correct since it's from the root of the vault. If `Beginning` is a folder in your vault and not the name of it you'll want to add that to the beginning of the path.

You'll also want the path in the template to match the path in your `meta-bind-button` code block for `folderPath`. If they don't match that could cause an issue as well.

As a last step, does the original template/button from Dann's page work as intended? It should create `Timestamps/Meetings` at the root of your vault.

Beyond that I'm not entirely sure why it wouldn't work for you. For what it's worth the error looks to be with the templater plugin and not meta bind based off the `plugin:templater-obsidian` bit. I'm guessing one of the modifications from the original is what's causing the issue, but I'm not too familiar with either plugin to really get to the bottom of it.

**Comment by mProjectsCode** [comment]
meta bind simply calls into the templater API, so the issue probably lies in templater and not meta bind.

https://github.com/mProjectsCode/obsidian-meta-bind-plugin/blob/c143a46f4830386aca1c7bc6bb0050d816c1a37b/packages/obsidian/src/ObsidianButtonActionRunner.ts#L14

**Comment by mProjectsCode** [comment]
I would guess this is either an issue with templater or your template.

**Comment by dzenifr** [comment]
It's possible. Thanks for the troubleshooting help!

**Comment by mProjectsCode** [comment]
I will close this issue for now. Should it become clear that this is an issue with meta bind and not templater or your template, I will reopen this.
