### ISSUE TITLE
Global Text Field Property for DataView Compat

### ISSUE THREAD

**Issue by GudBoiNero** [mProjectsCode/obsidian-meta-bind-plugin#281]
### Is your Feature Request Related to a Problem?

I've been using metabind quite a lot recently and I've noticed that when I use it in conjunction with DataView it often refreshes the view very quickly. I had to turn the refresh delay on DataView quite high but even then it's annoying to keep manually refreshing or waiting a while.

### Describe the Feature you'd Like

If possible it would be great to have a global property like `commitOnly` or `updateOnEnter` on things like the `editor` and `textArea` fields that makes it so it will only update the actual metadata of the file *once* when you actually *submit* and exit the area. This would prevent DataView from refreshing if you take a second or two long break from typing since DataView listens to file changes and not input events.

**Comment by mProjectsCode** [comment]
You can change the sync interval, which controls how often meta bind updates the frontmatter, in the meta bind settings.
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/61602848/9c169a85-e76f-489b-ad92-95aadb06ab6a)

Syncing only when a user finished typing is not really within the scope of the plugin. If dataview is too slow, then that is more a dataview issue, which could be fixed by dataview debouncing updates.
