### ISSUE TITLE
Feature Request: Button input triggering set value

### ISSUE THREAD

**Issue by ironfroggy** [mProjectsCode/obsidian-meta-bind-plugin#57]
**Is your feature request related to a problem? Please describe.**
I have several note templates that, after creating, default to read-view and I use meta-bind inputs to edit their information. One thing I can't do easily is edit tags because the multi_select will remove any values not listed as options, and I don't want to list ALL the possible tags just common ones.

**Describe the solution you'd like**
I propose two solutions, ideally both!

1. A new input type `button` that works like this:
> `INPUT(button(title(Fav), add(favorite)):tags)`
> `INPUT(button(title(Unfav), remove(favorite)):tags)`
> `INPUT(button(title(Reset), set()):tags)`
2. Allowing these `add`, `remove`, and `set` options be added to the toggle input:
> Favorite: `INPUT[toggle(on(add(favorite)), off(remove(favorite)):tags]`

Willing to work on a PR if it would be considered.

**Comment by mProjectsCode** [comment]
Great idea, but I would generalize it more. I would add a general argument that allows listening to certain events. E.g. `event` with `event(event_name, action)`. So your example would look like this:
```
INPUT[toggle(
event(toggleOn, add(favorite)), 
event(toggleOff, remove(favorite))
):tags]
```

I am currently working on a JS API for meta-bind similar to dataviewjs, here is a little preview
```js
const declaration = mb.createDeclaration(
	'select',
	[
		{type: 'option', value: 'd'},
		{type: 'option', value: 'e'},
	],
	'select'
);

const inputField = mb.createInputField(declaration, undefined, 'block');

ctx.addChild(inputField);
```

And for that JS API, there should be the option to add custom callbacks to the `event` argument.

This seems to be a bit more complicated, but it would be greatly appreciated if you want to work on a PR for this, as I have exams coming up next month and little time because of that.

**Comment by mProjectsCode** [comment]
done in b495086

**Comment by giittyy** [comment]
Whats the code needed to implement this?

**Comment by giittyy** [comment]
So this can't be done within the toggle button itself? like this:
INPUT[toggle(
event(toggleOn, add(favorite)), 
event(toggleOff, remove(favorite))
):tags]

**Comment by mProjectsCode** [comment]
No. It was never implemented like this. Otherwise it would be in the docs.

**Comment by mProjectsCode** [comment]
No. It was never implemented like this. Otherwise it would be in the docs.

**Comment by giittyy** [comment]
Should I make another request or this that not something you want to do?
